# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-04 10:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ('-created_at',)},
        ),
    ]
